{
 "title": "Services Monitoring (via Prometheus)",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "lob", "label": "LOB", "query": "label_values(lob)" },
   {
    "name": "domain",
    "label": "Domain",
    "query": "label_values({lob=~\"$lob$\"},domain)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values({lob=~\"$lob$\",domain=~\"$domain$\"},namespace)"
   },
   {
    "name": "app",
    "label": "App",
    "query": "label_values({lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\"},app)"
   },
   {
    "name": "profile",
    "label": "Env",
    "query": "label_values({lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\"},profile)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values({lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\"},pod)"
   }
  ]
 },
 "panels": [
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Heap Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (jvm_memory_used_bytes{area=\"heap\",lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"}) / sum (jvm_memory_max_bytes{area=\"heap\",lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"}) * 100",
     "seriesAggFn": "none",
     "tagsQL": "container_name=$app AND descriptor_name='memory/usage'",
     "timeAggFn": "avg",
     "type": "gauge"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (jvm_memory_used_bytes{area=\"heap\",lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"})"
    }
   ]
  },
  {
   "title": "Non Heap Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (jvm_memory_used_bytes{area=\"nonheap\",lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"}) / sum (jvm_memory_max_bytes{area=\"nonheap\",lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"}) * 100",
     "seriesAggFn": "none",
     "tagsQL": "container_name=$app AND descriptor_name='memory/usage'",
     "timeAggFn": "avg",
     "type": "gauge"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (jvm_memory_used_bytes{area=\"nonheap\",lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"})"
    }
   ]
  },
  {
   "title": "Total Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (jvm_memory_used_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"}) / sum (jvm_memory_max_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"}) * 100",
     "seriesAggFn": "none",
     "tagsQL": "container_name=$app AND descriptor_name='memory/usage'",
     "timeAggFn": "avg",
     "type": "gauge"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 20, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (jvm_memory_used_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"})"
    }
   ]
  },
  {
   "title": "Committed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (jvm_memory_committed_bytes{area=\"heap\",lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"})  "
    }
   ]
  },
  {
   "title": "Committed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (jvm_memory_committed_bytes{area=\"nonheap\",lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"})  "
    }
   ]
  },
  {
   "title": "Committed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 20, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (jvm_memory_committed_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"})  "
    }
   ]
  },
  {
   "title": "Max",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (jvm_memory_max_bytes{area=\"heap\",lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"})  "
    }
   ]
  },
  {
   "title": "Max",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (jvm_memory_max_bytes{area=\"nonheap\",lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"})  "
    }
   ]
  },
  {
   "title": "Max",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 20, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (jvm_memory_max_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"})  "
    }
   ]
  },
  {
   "title": "Memory Pressure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (jvm_memory_used_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  { "title": "JVM CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (process_cpu_usage{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"}) / 0.5 * 100"
    }
   ]
  },
  {
   "title": "CPU Pressure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 5, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (process_cpu_usage{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"}) * 10",
     "legendFormat": "CPU"
    }
   ]
  },
  { "title": "HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "All",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate (http_server_requests_seconds_count{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"}[1m])) * 100",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "2xx",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate (http_server_requests_seconds_count{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\",status=~\"2.*\"}[1m])) * 100",
     "legendFormat": "2xx"
    }
   ]
  },
  {
   "title": "4xx",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate (http_server_requests_seconds_count{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\",status=~\"4.*\"}[1m])) * 100",
     "legendFormat": "4xx"
    }
   ]
  },
  {
   "title": "5xx",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate (http_server_requests_seconds_count{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\",status=~\"5.*\"}[1m])) * 100",
     "legendFormat": "5xx"
    }
   ]
  }
 ]
}