{
 "title": "Spring Boot Statistics",
 "description": "Dashboard for Spring Boot2 Statistics(by micrometer-prometheus).",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "lob", "label": "Lob", "query": "label_values(lob)" },
   {
    "name": "domain",
    "label": "Domain",
    "query": "label_values({lob=~\"$lob$\"},domain)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values({lob=~\"$lob$\",domain=~\"$domain$\"},namespace)"
   },
   {
    "name": "app",
    "label": "App",
    "query": "label_values({lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\"}, app)"
   },
   {
    "name": "profile",
    "label": "Env",
    "query": "label_values({lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\"}, profile)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values({lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\"}, pod)"
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": "label_values(hikaricp_connections{pod=~\"$pod$\", app=\"$app\"}, pool)"
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": "label_values(jvm_memory_used_bytes{app=\"$app\", pod=~\"$pod$\", area=\"heap\"},id)"
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": "label_values(jvm_memory_used_bytes{app=\"$app\", pod=~\"$pod$\", area=\"nonheap\"},id)"
   }
  ]
 },
 "panels": [
  { "title": "Basic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(process_uptime_seconds{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"})"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Process Open Files",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(process_files_open_files{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"})",
     "legendFormat": "Open Files"
    },
    {
     "expr": "sum(process_files_max_files{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"})",
     "legendFormat": "Max Files"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"}*1000)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(system_cpu_usage{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"})",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "sum(process_cpu_usage{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"})",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(system_load_average_1m{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"})",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "sum(system_cpu_count{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"})",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  {
   "title": "JVM Statistics - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "$memory_pool_heap (heap)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "repeat": "memory_pool_heap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", id=\"$memory_pool_heap\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", id=\"$memory_pool_heap\"})",
       "legendFormat": "Commited"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", id=\"$memory_pool_heap\"})",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "$memory_pool_heap (heap)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", id=\"$memory_pool_heap\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", id=\"$memory_pool_heap\"})",
       "legendFormat": "Commited"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", id=\"$memory_pool_heap\"})",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "$memory_pool_heap (heap)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", id=\"$memory_pool_heap\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", id=\"$memory_pool_heap\"})",
       "legendFormat": "Commited"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", id=\"$memory_pool_heap\"})",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "$memory_pool_nonheap (non-heap)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "repeat": "memory_pool_nonheap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", id=\"$memory_pool_nonheap\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", id=\"$memory_pool_nonheap\"})",
       "legendFormat": "Commited"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", id=\"$memory_pool_nonheap\"})",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "$memory_pool_nonheap (non-heap)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", id=\"$memory_pool_nonheap\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", id=\"$memory_pool_nonheap\"})",
       "legendFormat": "Commited"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", id=\"$memory_pool_nonheap\"})",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "$memory_pool_nonheap (non-heap)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", id=\"$memory_pool_nonheap\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", id=\"$memory_pool_nonheap\"})",
       "legendFormat": "Commited"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", id=\"$memory_pool_nonheap\"})",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Classes Loaded",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_classes_loaded_classes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"})",
       "legendFormat": "Classes Loaded"
      }
     ]
    },
    {
     "title": "Classes Unloaded",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(jvm_classes_unloaded_classes_total{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"}[5m]))",
       "legendFormat": "Classes Unloaded"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_buffer_memory_used_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", id=\"direct\"})",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "sum(jvm_buffer_total_capacity_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", id=\"direct\"})",
       "legendFormat": "Capacity Bytes"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_buffer_memory_used_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", id=\"mapped\"})",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "sum(jvm_buffer_total_capacity_bytes{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", id=\"mapped\"})",
       "legendFormat": "Capacity Bytes"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_threads_daemon_threads{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"})",
       "legendFormat": "Daemon"
      },
      {
       "expr": "sum(jvm_threads_live_threads{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"})",
       "legendFormat": "Live"
      },
      {
       "expr": "sum(jvm_threads_peak_threads{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"})",
       "legendFormat": "Peak"
      }
     ]
    },
    {
     "title": "Memory Allocate/Promote",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(irate(jvm_gc_memory_allocated_bytes_total{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"}[5m]))",
       "legendFormat": "allocated"
      },
      {
       "expr": "sum(irate(jvm_gc_memory_promoted_bytes_total{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"}[5m]))",
       "legendFormat": "promoted"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Statistics - GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_count{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"}[5m])",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    },
    {
     "title": "GC Stop the World Duration",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_sum{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"}[5m])",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "HikariCP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections Size",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(hikaricp_connections{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", pool=\"$hikaricp\"})"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(hikaricp_connections_active{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", pool=\"$hikaricp\"})",
       "legendFormat": "Active"
      },
      {
       "expr": "sum(hikaricp_connections_idle{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", pool=\"$hikaricp\"})",
       "legendFormat": "Idle"
      },
      {
       "expr": "sum(hikaricp_connections_pending{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", pool=\"$hikaricp\"})",
       "legendFormat": "Pending"
      }
     ]
    },
    {
     "title": "Connection Timeout Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(hikaricp_connections_timeout_total{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", pool=\"$hikaricp\"})"
      }
     ]
    },
    {
     "title": "Connection Creation Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_creation_seconds_sum{pod=\"$pod\", app=\"$app\", pool=\"$hikaricp\"} / hikaricp_connections_creation_seconds_count{pod=\"$pod\", app=\"$app\", pool=\"$hikaricp\"}",
       "legendFormat": "Creation Time"
      }
     ]
    },
    {
     "title": "Connection Usage Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_usage_seconds_sum{pod=\"$pod\", app=\"$app\", pool=\"$hikaricp\"} / hikaricp_connections_usage_seconds_count{pod=\"$pod\", app=\"$app\", pool=\"$hikaricp\"}",
       "legendFormat": "Usage Time"
      }
     ]
    },
    {
     "title": "Connection Acquire Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_acquire_seconds_sum{pod=\"$pod\", app=\"$app\", pool=\"$hikaricp\"} / hikaricp_connections_acquire_seconds_count{pod=\"$pod\", app=\"$app\", pool=\"$hikaricp\"}",
       "legendFormat": "Acquire Time"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_count{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", uri!~\".*actuator.*\"}[5m])",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_sum{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", exception=\"None\", uri!~\".*actuator.*\"}[5m]) / irate(http_server_requests_seconds_count{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", exception=\"None\", uri!~\".*actuator.*\"}[5m])",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tomcat Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Error Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
     "format": "locale",
     "valueName": "current",
     "targets": [
      {
       "expr": "tomcat_global_error_total{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"}"
      }
     ]
    },
    {
     "title": "Active Sessions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 4, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "tomcat_sessions_active_current_sessions{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"}",
       "legendFormat": "active sessions"
      }
     ]
    },
    {
     "title": "Sent & Recieved Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(tomcat_global_sent_bytes_total{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"}[5m])",
       "legendFormat": "Sent Bytes"
      },
      {
       "expr": "irate(tomcat_global_received_bytes_total{pod=\"$pod\", app=\"$app\"}[5m])",
       "legendFormat": "Recieved Bytes"
      }
     ]
    },
    {
     "title": "Thread Config Max",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
     "format": "locale",
     "valueName": "current",
     "targets": [
      {
       "expr": "tomcat_threads_config_max_threads{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tomcat_threads_current_threads{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"}",
       "legendFormat": "Current thread"
      },
      {
       "expr": "tomcat_threads_busy_threads{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\"}",
       "legendFormat": "Current thread busy"
      }
     ]
    }
   ]
  },
  {
   "title": "Logback Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "INFO logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(logback_events_total{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", level=\"info\"}[5m])",
       "legendFormat": "info",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "ERROR logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(logback_events_total{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", level=\"error\"}[5m])",
       "legendFormat": "error",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "WARN logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(logback_events_total{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", level=\"warn\"}[5m])",
       "legendFormat": "warn",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "DEBUG logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(logback_events_total{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", level=\"debug\"}[5m])",
       "legendFormat": "debug",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "TRACE logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(logback_events_total{lob=~\"$lob$\",domain=~\"$domain$\",namespace=~\"$namespace$\",app=~\"$app$\",profile=~\"$profile$\",pod=~\"$pod$\", level=\"trace\"}[5m])",
       "legendFormat": "trace",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    }
   ]
  }
 ]
}